Instructions for the assignment


*   Fill the codeblocks according to the comments given
*   Hints are given wherever required
*   Please note that copying will not be tolerated, and appropriate action will be taken if we suspect any misconduct.
*   You're welcome to utilize any online resources in case you feel stuck anywhere :-)

# Section A *(2 Marks each)*

## NumPy (Numerical Python)
**bold text**
### Multidimensional array object
- Array is a grid of homogeneous elements which can be indexed in various ways 
- Different from Python list which can store different data types
- NumPy stores multidimensional arrays as an instance of **ndarray**

In [ ]:
import numpy as np

In [ ]:
# Python list to initialize a one dimensional NumPy array of numbers 1 to 5 and then print it 
arr = np.array([1,2,3,4,5])
print(arr)

# Python list to initialize a two dimensional NumPy array of shape [3,3] and then print it 
arr = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(arr)

[1 2 3 4 5]
[[1 2 3]
 [4 5 6]
 [7 8 9]]

In [ ]:
# Write a NumPy function to create an array with random values of shape [3,4]
arr = np.random.rand(3,4)
print(arr)

# Write a NumPy function to create an array with all elements initialized as zero of shape [3,4]
arr = np.zeros((3,4))
print(arr)

# Write a NumPy function to create an array with all elements initialized as ones of shape [3,4]
arr = np.ones((3,4))
print(arr)

[[0.64167342 0.87748666 0.45258547 0.2138362 ]
 [0.80545636 0.3597107  0.13665964 0.92808223]
 [0.63629659 0.69856618 0.10864993 0.5308883 ]]
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]

In [ ]:
# Write a NumPy function to create an array containing a range of evenly spaced intervals
# Hint : Use np.arange or np.linspace
def create_interval_array(start, end, num_intervals):
    return np.linspace(start, end, num_intervals)
    
start = 0
end = 10
num_intervals = 11

interval_array = create_interval_array(start, end, num_intervals)
print(interval_array)

[ 0.  1.  2.  3.  4.  5.  6.  7.  8.  9. 10.]

### Basic array operations
- algebraic operations 
- logical operations

In [ ]:
a = np.array([[-4,6,8], [9, 3, 1], [1, 8, 5]])
b = np.array([[11,16,18], [90, 37, 81], [61, 48, 75]])

In [ ]:
# Write a NumPy function to add, subtract, multiply and divide arrays 'a' and 'b'
x = np.add(a,b)
y = np.subtract(a,b)
z = np.multiply(a,b)
w = np.divide(a,b)
print(x)
print(y)
print(z)
print(w)

[[ 7 22 26]
 [99 40 82]
 [62 56 80]]
[[-15 -10 -10]
 [-81 -34 -80]
 [-60 -40 -70]]
[[-44  96 144]
 [810 111  81]
 [ 61 384 375]]
[[-0.36363636  0.375       0.44444444]
 [ 0.1         0.08108108  0.01234568]
 [ 0.01639344  0.16666667  0.06666667]]

In [ ]:
# Write a NumPy function to get the sum of the array 'a' along axis=0 
def sum_along_axis_0(arr):
    return np.sum(arr, axis=0)

a = np.array([[-4,6,8], [9, 3, 1], [1, 8, 5]])

result = sum_along_axis_0(a)
print(result)

# Write a NumPy function to get the sum of the array 'a' along axis=1 
def sum_along_axis_1(arr):
    return np.sum(arr, axis=1)

a = np.array([[-4,6,8], [9, 3, 1], [1, 8, 5]])

result = sum_along_axis_1(a)
print(result)

[ 6 17 14]
[10 13 14]

In [ ]:
# Write a NumPy function to reverse the array 'a' 
newarr = np.flip(a)
print(newarr)

# Write a NumPy function to reverse the array 'a' along axis=0
def flip_along_axis_0(arr):
  return np.flip(arr,axis=0)

a = np.array([[-4,6,8], [9, 3, 1], [1, 8, 5]])

result = flip_along_axis_0(a)
print(result)
  

# Write a NumPy function to reverse the array 'a' along axis=1
def flip_along_axis_1(arr):
  return np.flip(arr,axis=1)

a = np.array([[-4,6,8], [9, 3, 1], [1, 8, 5]])

result = flip_along_axis_1(a)
print(result)

[[ 5  8  1]
 [ 1  3  9]
 [ 8  6 -4]]
[[ 1  8  5]
 [ 9  3  1]
 [-4  6  8]]
[[ 8  6 -4]
 [ 1  3  9]
 [ 5  8  1]]

### Sorting and concatenation
- sort arrays
- join multiple arrays

In [ ]:
a = np.array([[-4,6,8], [9, 3, 1], [1, 8, 5]])
b = np.array([[11,16,18], [90, 37, 81], [61, 48, 75]])

In [ ]:
# Write a NumPy function to sort the array 'a' 
print(np.sort(a))

# Write a NumPy function to sort the array 'a' along axis=0

def sort_along_axis_0(arr):
  return np.sort(arr,axis=0)

a = np.array([[-4,6,8], [9, 3, 1], [1, 8, 5]])

result = sort_along_axis_0(a)
print(result)

# Write a NumPy function to sort the array 'a' along axis=1

def sort_along_axis_1(arr):
  return np.sort(arr,axis=1)

a = np.array([[-4,6,8], [9, 3, 1], [1, 8, 5]])

result = sort_along_axis_1(a)
print(result)

# Write a NumPy function to sort the array 'a' in descending order along axis=0

import numpy as np

def sort_descending_axis_0(arr):
    sorted_arr = np.sort(arr, axis=0)
    return np.flip(sorted_arr, axis=0)

a = np.array([[-4, 6, 8], [9, 3, 1], [1, 8, 5]])
result = sort_descending_axis_0(a)
print(result)

[[-4  6  8]
 [ 1  3  9]
 [ 1  5  8]]
[[-4  3  1]
 [ 1  6  5]
 [ 9  8  8]]
[[-4  6  8]
 [ 1  3  9]
 [ 1  5  8]]
[[ 9  8  8]
 [ 1  6  5]
 [-4  3  1]]

In [ ]:
# Write a NumPy function to argsort the array along axis=0

def argsort_along_axis_0(arr):
    return np.argsort(arr, axis=0)

a = np.array([[-4, 6, 8], [9, 3, 1], [1, 8, 5]])
result = argsort_along_axis_0(a)
print(result)

# Write a NumPy function to argsort the array along axis=1

def argsort_along_axis_1(arr):
    return np.argsort(arr, axis=1)

a = np.array([[-4, 6, 8], [9, 3, 1], [1, 8, 5]])
result = argsort_along_axis_1(a)
print(result)

[[0 1 1]
 [2 0 2]
 [1 2 0]]
[[0 1 2]
 [2 1 0]
 [0 2 1]]

In [ ]:
# Write a NumPy function to concatenate the arrays 'a' and 'b'
def concatenate_arrays(arr1, arr2):
    return np.concatenate((arr1, arr2))

result = concatenate_arrays(a, b)
print(result)

# Write a NumPy function to concatenate the arrays 'a' and 'b' along axis = 0
def concatenate_arrays_along_axis_0(arr1, arr2):
    return np.concatenate((arr1, arr2))

result = concatenate_arrays_along_axis_0(a, b)
print(result)

# Note: You can do the same function using stacking, discover and try that :)
def concatenate_arrays_axis_0(arr1, arr2):
    return np.vstack((arr1, arr2))

result = concatenate_arrays_axis_0(a, b)
print(result)

[[-4  6  8]
 [ 9  3  1]
 [ 1  8  5]
 [11 16 18]
 [90 37 81]
 [61 48 75]]
[[-4  6  8]
 [ 9  3  1]
 [ 1  8  5]
 [11 16 18]
 [90 37 81]
 [61 48 75]]
[[-4  6  8]
 [ 9  3  1]
 [ 1  8  5]
 [11 16 18]
 [90 37 81]
 [61 48 75]]

### Reshaping arrays
- the number of dimensions of the array
-  shape of n-dimensional array as a tuple with n elements s.t. $i^{th}$ element is the length of the $i^{th}$ dimension of the array
- total number of elements of the array
- reshapes the array
- flattens multidimensional array into a 1D array
- adds new dimensions to the array

In [ ]:
a = np.array([[4,6,8], [9, 3, 1], [1, 8, 5]])

In [ ]:
# Write a NumPy function to get the Number of dimensions
print(a.ndim)

# Write a NumPy function to get the Shape of the array  
print(a.shape)

# Write a NumPy function to get the Size of the array
print(a.size)

2
(3, 3)
9

In [ ]:
# Write a NumPy function to Reshape the array 'a' to the dimension (1,9)
newarr = a.reshape(1,9)
print(newarr)

[[4 6 8 9 3 1 1 8 5]]

In [ ]:
# Write a NumPy function to add a new axis to the array 'a' 
# Note : Show atleast two different ways of doing this 
import numpy as np

def add_new_axis_method1(a):
  new_array = a[np.newaxis, :]
  return new_array

def add_new_axis_method2(a):
  new_array = np.expand_dims(a, axis=0)
  return new_array

new_array_method1 = add_new_axis_method1(a)
print("Method 1:")
print(new_array_method1)

new_array_method2 = add_new_axis_method2(a)
print("Method 2:")
print(new_array_method2)

Method 1:
[[[4 6 8]
  [9 3 1]
  [1 8 5]]]
Method 2:
[[[4 6 8]
  [9 3 1]
  [1 8 5]]]

### Indexing and slicing
- NumPy allows indexing array using tuple of nonnegative integers, booleans, array or integers

In [ ]:
a = np.array([[4,6,0], [0, 3, 1], [1, 8, 5]])

In [ ]:
# Write a NumPy function to index and slice NumPy arrays similar to Python lists
# Show all three - indexing by a integer, indexing by a tuple, using range
import numpy as np
def indexing_example(arr):
    element = arr[2]
    #indexing by a integer
    print("Element at index 2:", element)

    #indexing by a tuple
    subarray = arr[1, 2]
    print("Element at index (1, 2):", subarray)

    #indexing by using a range
    sliced_array = arr[1:3, 0:2]
    print("Sliced array:\n", sliced_array)

a = np.array([[4,6,0], [0, 3, 1], [1, 8, 5]])
indexing_example(a)

Element at index 2: [1 8 5]
Element at index (1, 2): 1
Sliced array:
 [[0 3]
 [1 8]]

In [ ]:
# Write a NumPy function to select values satisfying a specific condition like Values greater than 4 
import numpy as np
def value_greater_than(arr, given):
  mask = arr > given
  final_values = arr[mask]

  return final_values
a = np.array([[4,6,0], [0, 3, 1], [1, 8, 5]])
result = value_greater_than(a, 4)

print(result)

# Write a NumPy function to select values satisfying mulitple conditions like Values greater than 4 and divisible by 2
def value_with_conditions(arr):
  mask1 = arr > 4
  mask2 = arr % 2 == 0
  combined_mask = np.logical_and(mask1, mask2)
  
  final_array = arr[combined_mask]
  return final_array

a = np.array([[4,6,0], [0, 3, 1], [1, 8, 5]])

result = value_with_conditions(a)
print(result)

[6 8 5]
[6 8]

### Copying arrays
- new array object with a copy of the data
- Changes made in the copy array is not reflected in the original array

In [ ]:
a = np.array([[4,6,0], [0, 3, 1], [1, 8, 5]])

In [ ]:
# Write a NumPy function to copy the array 'a' and finally print an array where all elements are increased by 1
def copy_and_increase(arr):
  arr_copy = np.copy(arr)
  arr_copy += 1
  return arr_copy
   
result = copy_and_increase(a)
print(result)

[[5 7 1]
 [1 4 2]
 [2 9 6]]

## Pandas ( Python Data Analysis Library)

### Main Features
- Easy handling of missing data in both floating point and non-floating point data.
- Automatic and explicit data alignment, making it easy to perform computations and transformations on data sets.

#### Generating the dataset

Run the following load command to get the 2-Dim iris dataset. Do the following operations on it and please dont edit this cell

In [ ]:
import numpy as np
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris_2d = np.genfromtxt(url, delimiter=',', dtype='float', usecols=[0,1,2,3])

#### Basic Data Analysis

In [ ]:
# Write a Pandas function to drop rows that contain a missing value. 
import pandas as pd
def drop_rows_with_missing(df):
  df.dropna()
  return df

df = pd.DataFrame(iris_2d)
df = drop_rows_with_missing(df)
print(df)

       0    1    2    3
0    5.1  3.5  1.4  0.2
1    4.9  3.0  1.4  0.2
2    4.7  3.2  1.3  0.2
3    4.6  3.1  1.5  0.2
4    5.0  3.6  1.4  0.2
..   ...  ...  ...  ...
145  6.7  3.0  5.2  2.3
146  6.3  2.5  5.0  1.9
147  6.5  3.0  5.2  2.0
148  6.2  3.4  5.4  2.3
149  5.9  3.0  5.1  1.8

[150 rows x 4 columns]

In [ ]:
# Write a Pandas function to find the correlation between the first two columns.
import pandas as pd
def find_correlation(df):
    subset = df.iloc[:, 0:2]
    
    correlation = subset.corr()
    
    return correlation
    df = pd.DataFrame(iris_2d)

correlation = find_correlation(df)

print(correlation)

          0         1
0  1.000000 -0.109369
1 -0.109369  1.000000

In [ ]:
# Write a Pandas function to find the mean, median and standard deviation of column 3.
import pandas as pd
def calculate_stats(df,column):
  mean = df[column].mean()
  median = df[column].median()
  std_dev = df[column].std()

  return mean,median,std_dev
df = pd.DataFrame(iris_2d)
mean,median,std_dev= calculate_stats(df, 3)

print("Mean:",mean)
print("Median:", median)
print("Standard Deviation:", std_dev)

Mean: 1.1986666666666668
Median: 1.3
Standard Deviation: 0.7631607417008411

In [79]:
# Write a Pandas function to create a new column for volume in iris_2d, where volume is (pi x petallength x sepal_length^2)/3
# Hints: 
# 1. Introduce new dimension to match iris_2d's
# 2. Add the new column
import pandas as pd
import numpy as np
from math import pi

def add_volume_column(data):
   volume = (pi * data['petallength'] * data['sepallength']**2) / 3

   data['volume'] = volume
   return data
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris_2d = pd.read_csv(url, header=None, names=['sepallength', 'sepalwidth', 'petallength', 'petalwidth', 'species'])

iris_2d_with_volume = add_volume_column(iris_2d)

print(iris_2d_with_volume)

     sepallength  sepalwidth  petallength  petalwidth         species  \
0            5.1         3.5          1.4         0.2     Iris-setosa
1            4.9         3.0          1.4         0.2     Iris-setosa
2            4.7         3.2          1.3         0.2     Iris-setosa
3            4.6         3.1          1.5         0.2     Iris-setosa
4            5.0         3.6          1.4         0.2     Iris-setosa
..           ...         ...          ...         ...             ...
145          6.7         3.0          5.2         2.3  Iris-virginica
146          6.3         2.5          5.0         1.9  Iris-virginica
147          6.5         3.0          5.2         2.0  Iris-virginica
148          6.2         3.4          5.4         2.3  Iris-virginica
149          5.9         3.0          5.1         1.8  Iris-virginica

         volume
0     38.132652
1     35.200498
2     30.072372
3     33.238050
4     36.651914
..          ...
145  244.445230
146  207.816354
147  230.069302
148  217.373079
149  185.910028

[150 rows x 6 columns]

# Section B *(2 Marks each)*

###NumPy

Q1 Let x = np.arange(4, dtype=np.int64). Create an array of ones with the same shape and type as X.

In [ ]:
import numpy as np

x = np.arange(4, dtype=np.int64)
ones_array = np.ones_like(x)

print(ones_array)

[1 1 1 1]

Q2 Let x be an array [1, 2, 3, ..., 9]. Split x into 3 arrays, each of which has 4, 2, and 3 elements in the original order.

In [ ]:
import numpy as np

x = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])
splitted_arrays = np.split(x, [4, 6])

print(splitted_arrays)

[array([1, 2, 3, 4]), array([5, 6]), array([7, 8, 9])]

Q3 Initiate x as a 2x5 array with random values from 0 to 10(not inclusive).Get the maximum and minimum values and their indices of x along the second axis.

In [ ]:
import numpy as np

x = np.random.randint(0, 10, size=(2,5))

max_value = np.max(x, axis=1)
min_value = np.min(x, axis=1)

max_indices = np.argmax(x, axis=1)
min_indices = np.argmin(x, axis=1)

print("Maximum values along the second axis:", max_value)
print("Indices of maximum values along the second axis:", max_indices)
print("Minimum values along the second axis:", min_value)
print("Indices of minimum vlaue along the second axis:", min_indices)

Maximum values along the second axis: [7 5]
Indices of maximum values along the second axis: [1 0]
Minimum values along the second axis: [0 1]
Indices of minimum vlaue along the second axis: [0 2]

### Pandas

Run the following load command and solve the following questions

In [ ]:
import numpy as np
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris = np.genfromtxt(url, delimiter=',', dtype='object')
names = ('sepallength', 'sepalwidth', 'petallength', 'petalwidth', 'species')

Q4 Write a Pandas function to find the count of unique species.

In [ ]:
import pandas as pd

def count_unique_species(data):
  unique_species = data.nunique()
  return unique_species

data = pd.DataFrame(iris)
count = count_unique_species(data)  

print("Count of the number of unique species:", count)

Count of the number of unique species: 0    35
1    23
2    43
3    22
4     3
dtype: int64

# Q5 Write a Pandas function to bin the petal length (3rd) column of iris_2d to form a text array, such that if petal length is:
- Less than 3 –> ‘small’
- 3-5 –> ‘medium’
- greater than equal to 5 –> ‘large’

In [78]:
import pandas as pd

def bin_petal_length(data):
    data['petal_length_bin'] = pd.cut(data['petallength'], bins=[0, 3, 5, float('inf')], labels=['small', 'medium', 'large'], right=False)
    
    return data
import numpy as np

url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris_2d = pd.read_csv(url, header=None, names=['sepallength', 'sepalwidth', 'petallength', 'petalwidth', 'species'])

iris_2d_binned = bin_petal_length(iris_2d)

print(iris_2d_binned)

     sepallength  sepalwidth  petallength  petalwidth         species  \
0            5.1         3.5          1.4         0.2     Iris-setosa
1            4.9         3.0          1.4         0.2     Iris-setosa
2            4.7         3.2          1.3         0.2     Iris-setosa
3            4.6         3.1          1.5         0.2     Iris-setosa
4            5.0         3.6          1.4         0.2     Iris-setosa
..           ...         ...          ...         ...             ...
145          6.7         3.0          5.2         2.3  Iris-virginica
146          6.3         2.5          5.0         1.9  Iris-virginica
147          6.5         3.0          5.2         2.0  Iris-virginica
148          6.2         3.4          5.4         2.3  Iris-virginica
149          5.9         3.0          5.1         1.8  Iris-virginica

    petal_length_bin
0              small
1              small
2              small
3              small
4              small
..               ...
145            large
146            large
147            large
148            large
149            large

[150 rows x 6 columns]

Q6 Write a Pandas function to find the most frequent value of petal length (3rd column) in iris dataset

In [80]:
import pandas as pd

def frequent_petal_length(url):
    iris = pd.read_csv(url, header=None, names=('sepallength', 'sepalwidth', 'petallength', 'petalwidth', 'species'))
    
    most_frequent_value = iris['petallength'].mode().values[0]
    
    return most_frequent_value
    url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'

most_frequent_value = frequent_petal_length(url)

print("Most frequent value of petal length:", most_frequent_value)

Most frequent value of petal length: 1.5